version: '3.8'

services:
  app:
    build: .
    depends_on:
      - elasticsearch
      - kibana
    container_name: lib
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    network_mode: bridge
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single_node
      - 'ES_JAVA_OPTS=Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    network_mode: bridge
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
